Feature: Basic Robot Simulator
cmrobotics/cmr_tests_utils pull request #5
Opened 2022-05-17 17:25 UTC by guilyx

## Purpose
There are a fair amount of untested packages, because we had no ways to simply emulate the movements of a robot. (i.e. `docking_controller`, `relative_move`...)

## Approach
Here I developed a Node that listens to a `velocity` topic and broadcasts a projected `global_frame` to `base_frame` transform. It of cours abstracts all hardware issues and assumes the kinematic model is perfect.

2022-05-17 19:02 UTC, jcmonteiro commented
How do you think this compares to running gzserver in the CI? Maybe we will have use cases for both?

2022-05-17 19:05 UTC, guilyx commented
This is fine for unit testing methods, gzserver is suited for things that require running the stack imo
Ex: gzserver is good if you need to run a test that needs a map and proper instantiation of the whole stack, this is good for testing minimal things like "when I request rotating 90 degrees, are the commands received actually going to get me to 90 degrees"

2022-05-17 19:14 UTC, guilyx commented
@SomaGallai fyi the last commit broke the CI but it's still building locally

2022-05-18 08:01 UTC, TanmayDeshmukh approved these changes, later dismissed

2022-05-19 09:15 UTC, jcmonteiro requested changes
I would approve if not for the `#include` syntax. It is a detail, but we should keep it consistent so that others copy the correct syntax when using this code as reference.

2022-05-19 09:15 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +    return *last_received_vel_;
Just a tiny detail, but I believe it would be more elegant to return a `geometry_msgs::msg::Twist::ConstSharedPtr` here. It takes advantage of the `shared_ptr` you already store, making it `const` to prevent modifications.

2022-05-19 09:15 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +#include "geometry_msgs/msg/twist.hpp"
Small detail here, but including with `#include <>` should be preferred for headers that reside outside of the project.

2022-05-19 09:15 UTC, jcmonteiro commented on include/cmr_tests_utils/basic_tf_broadcaster_node_test.hpp
> -    RCLCPP_ERROR(get_logger(), "Fuck you");
What the hell? :rofl:

2022-05-19 09:20 UTC, cmraaron commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +#include "geometry_msgs/msg/twist.hpp"
usually these are just for the C++ standard library headers right? like `<chrono>` is here, but libs like ros for example are typically in `""`

eg https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

2022-05-19 09:24 UTC, cmraaron commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +#include "geometry_msgs/msg/twist.hpp"
then there is this guidance
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-incform

perhaps this is more in line with what we want?

2022-05-19 09:38 UTC, guilyx commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +#include "geometry_msgs/msg/twist.hpp"
I'm used to the first style, but I actually like the second one better so I'm find for changing to this.
If we do go for that, @jcmonteiro could you add some of this to the `.github` repository ?

2022-05-19 09:39 UTC, guilyx commented on include/cmr_tests_utils/basic_tf_broadcaster_node_test.hpp
> -    RCLCPP_ERROR(get_logger(), "Fuck you");
It was getting very frustrating haha

2022-05-19 11:40 UTC, SomaGallai approved these changes, later dismissed

2022-05-19 11:54 UTC, SomaGallai commented
When this gets merged, can you create a new tag please. https://github.com/cmrobotics/odom_tf_publisher/pull/1 is failing due to tests_utils not being up-to-date.

2022-05-19 17:22 UTC, TanmayDeshmukh approved these changes, later dismissed

2022-05-25 09:59 UTC, jcmonteiro requested changes
The PR is looking really good! I just made some small comments to help improve it a little bit, but you could even see them as optional.

To document what we briefly talked about, I would favor passing `ros::Time` and `ros::Duration` objects or plain `std::chrono` whenever time variables are used. This is to prevent a developer messing up the function call. For example, thinking the function receives a `uint64_t` value in milliseconds when it actually is a `double` value in seconds.

2022-05-25 09:59 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +#define SIMULATED_DIFFERENTIAL_ROBOT
This applies to all the headers. You can replace the `#ifndef` and friends with a single call to `#pragma once` at the top of your header file.

2022-05-25 09:59 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +      std::chrono::milliseconds(int(broadcast_period_sec_*1000)),
I believe this is "old-style casting" and that it has been replaced by `static_cast<int>(...)`

2022-05-25 09:59 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +      std::chrono::duration<double> elapsed_time = std::chrono::system_clock::now() - last_velocity_timestamp_;
I believe you should favor a `get_clock()->now()` or a similar call here.

2022-05-25 09:59 UTC, jcmonteiro commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +    last_velocity_timestamp_ = std::chrono::system_clock::now();
Same as the other comment about using a "ROS" clock

2022-05-25 09:59 UTC, jcmonteiro commented on package.xml
> +  <build_depend>tf2_kdl</build_depend>
Do you need `tf2_kdl`? Maybe you should be using `tf2_geometry_msgs` instead for the `tf2::toMsg` and friends?

2022-05-25 09:59 UTC, jcmonteiro commented on test/simulated_robot_test.cpp
> +  ASSERT_NEAR(robot->get_transform().transform.rotation.w, 1.0, 0.01);
These assertions _could_ fail "randomly" in a CI since it depends on sleeping. I think it is fine for now, but I just wanted to leave the comment here.

2022-05-25 16:01 UTC, guilyx commented on include/cmr_tests_utils/simulated_differential_robot.hpp
> +      std::chrono::duration<double> elapsed_time = std::chrono::system_clock::now() - last_velocity_timestamp_;
I'd rather use modern C++ features and avoid using rclcpp things when I can if you don't mind :p

2022-05-29 14:41 UTC, TanmayDeshmukh submitted a review, later dismissed

2022-05-31 09:06 UTC, cmraaron commented on include/cmr_tests_utils/base_rclpp_test_fixture.hpp
> +#pragma once
I think, if you are going to use `#pragma once` you dont head the traditional header guard above it

2022-05-31 20:07 UTC, guilyx commented on include/cmr_tests_utils/base_rclpp_test_fixture.hpp
> +#pragma once
https://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards

It's a tough discussion apparently haha

2022-05-31 20:14 UTC, guilyx commented on include/cmr_tests_utils/base_rclpp_test_fixture.hpp
> +#pragma once
But I don't think we're in the case where both should be useful so I guess `#pragma once` it is

2022-06-02 14:54 UTC, merged